import AppColors from '../constants/AppColors';
import {MD3LightTheme as DefaultTheme} from 'react-native-paper';

export default {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: AppColors.primary,
    onPrimary: AppColors.pureWhite,
    primaryContainer: AppColors.pureWhite,
    onPrimaryContainer: AppColors.primary,
    secondary: AppColors.secondary,
    onSecondary: AppColors.pureWhite,
    secondaryContainer: AppColors.pureWhite,
    onSecondaryContainer: AppColors.secondary,
    tertiary: 'rgb(127, 85, 58)',
    onTertiary: AppColors.pureWhite,
    tertiaryContainer: AppColors.pureWhite,
    onTertiaryContainer: AppColors.pureWhite,
    error: AppColors.error,
    onError: AppColors.pureWhite,
    errorContainer: 'rgb(255, 218, 214)',
    onErrorContainer: 'rgb(65, 0, 2)',
    background: AppColors.background,
    onBackground: AppColors.textDefault,
    surface: 'rgb(255, 251, 255)',
    onSurface: 'rgb(31, 26, 28)',
    surfaceVariant: 'rgb(241, 222, 228)',
    onSurfaceVariant: 'rgb(80, 67, 72)',
    outline: AppColors.primary,
    outlineVariant: 'rgb(212, 194, 200)',
    shadow: 'rgb(0, 0, 0)',
    scrim: 'rgb(0, 0, 0)',
    inverseSurface: 'rgb(53, 47, 49)',
    inverseOnSurface: 'rgb(249, 238, 240)',
    inversePrimary: 'rgb(255, 175, 212)',
    elevation: {
      level0: 'transparent',
      level1: AppColors.pureWhite,
      level2: AppColors.pureWhite,
      level3: AppColors.pureWhite,
      level4: AppColors.pureWhite,
      level5: AppColors.pureWhite,
    },
    surfaceDisabled: 'rgba(31, 26, 28, 0.12)',
    onSurfaceDisabled: 'rgba(31, 26, 28, 0.38)',
    backdrop: 'rgba(57, 45, 50, 0.4)',
  } as const,
};
