package com.onegini.mobile.rnexampleapp;

import android.os.Build;
import com.onegini.mobile.sdk.android.model.OneginiClientConfigModel;

public class OneginiConfigModel implements OneginiClientConfigModel {

  /* Config model generated by SDK Configurator version: v5.1.0 */

  private final String appIdentifier = "RNExampleApp";
  private final String appPlatform = "android";
  private final String redirectionUri = "reactnativeexample://loginsuccess";
  private final String appVersion = "0.1.0";
  private final String baseURL = "https://token-mobile.test.onegini.com";
  private final String resourceBaseURL = "https://token-mobile.test.onegini.com/resources/";
  private final String keystoreHash = "a939e1d2f3926f16224d8425c98743fdd39856c6d7199332ffb4327f513ee7f6";
  private final int maxPinFailures = 5;
  private final String serverPublicKey = null;

  public String getAppIdentifier() {
    return appIdentifier;
  }

  public String getAppPlatform() {
    return appPlatform;
  }

  public String getRedirectUri() {
    return redirectionUri;
  }

  public String getAppVersion() {
    return appVersion;
  }

  public String getBaseUrl() {
    return baseURL;
  }

  public String getResourceBaseUrl() {
    return resourceBaseURL;
  }

  public int getCertificatePinningKeyStore() {
    return R.raw.keystore;
  }

  public String getKeyStoreHash() {
    return keystoreHash;
  }

  public String getDeviceName() {
    return Build.BRAND + " " + Build.MODEL;
  }

  public String getServerPublicKey() {
    return serverPublicKey;
  }

  /**
   * @Deprecated Since Android SDK 8.0.0 this attribute is not required.
   */
  public boolean shouldGetIdToken() {
    return false;
  }

  /**
   * Get the max PIN failures. This attribute is just used for visual
   * representation towards the end-user.
   *
   * @Deprecated Since Android SDK 6.01.00 this attribute is fetched from the
   *             Device config.
   *
   * @return The max PIN failures
   */
  public int getMaxPinFailures() {
    return maxPinFailures;
  }

  @Override
  public String toString() {
    return "ConfigModel{" +
        "  appIdentifier='" + appIdentifier + "'" +
        ", appPlatform='" + appPlatform + "'" +
        ", redirectionUri='" + redirectionUri + "'" +
        ", appVersion='" + appVersion + "'" +
        ", baseURL='" + baseURL + "'" +
        ", maxPinFailures='" + maxPinFailures + "'" +
        ", resourceBaseURL='" + resourceBaseURL + "'" +
        ", keyStoreHash='" + getKeyStoreHash() + "'" +
        ", serverPublicKey='" + serverPublicKey + "'" +
        "}";
  }
}
